### ISSUE TITLE
App build issue

### ISSUE THREAD

**Issue by jixu1031** [drogatkin/Atjeews#5]
I downloaded Android Studio and imported this Atjeews project to build.
But when I imported this project, it shows many class errors.
![image](https://user-images.githubusercontent.com/48024874/120218907-5d776500-c275-11eb-8fe0-61bee78fc7fb.png)
So could you please attach the guide to teach how to build this app and which libraries it needs?

**Comment by drogatkin** [comment]
I use 7Bee based build script: https://github.com/drogatkin/Atjeews/blob/master/bee-build.xml , you may need to edit the script in dependency on your environment. However, you can try to build a Gradle script and build the project directly from Android studio. You can use the article https://www.linkedin.com/pulse/how-migrate-android-project-use-gradle-build-tool-dmitriy-rogatkin/ helping to create a Gradle script. It is important that content of directory /META-INF/services/ included in the result APK to provide working of websocket correctly.

**Comment by jixu1031** [comment]
To build the script, bee-build.xml, we should build the 7Bee build tool and install, right?
When I ran bootstrap script, it shows such error.
![image](https://user-images.githubusercontent.com/48024874/120422202-9fa7b180-c31c-11eb-8387-c7a80d7e850d.png)
Maybe the central.maven.org to download jsch-0.1.53.jar was gone?
If the bootstrap script is successfully ran, we should run this command `java -jar ./lib/bee.jar install` to install 7Bee build tool?

**Comment by jixu1031** [comment]
I have more questions about bee-build.xml.
You defined the dependencies like this in the script. Could you possibly let me know where I can get each one?
![Screenshot from 2021-06-01 21-20-13](https://user-images.githubusercontent.com/48024874/120423524-73d9fb00-c31f-11eb-8840-8715ad69832c.png)
1. I downloaded the SDK Platform-tools for linux and copied in my working directory `/home/james/Android/Sdk` like this. Is it right?
![Screenshot from 2021-06-01 21-31-28](https://user-images.githubusercontent.com/48024874/120424364-0a5aec00-c321-11eb-86cb-f646aa491d42.png)

2. Could you please let me know where I can get `jasper-7.0.75`?

**Comment by jixu1031** [comment]
Dear drogatkin, could you please teach me what I should do?

**Comment by jixu1031** [comment]
My Java version is like this.
![image](https://user-images.githubusercontent.com/48024874/120476677-b6bbc300-c35f-11eb-9324-fb7c4de8f511.png)
Is it ok to build the app? `jdk 1.8.*` or another up-to-date Java version is also ok for this project?

**Comment by drogatkin** [comment]
> To build the script, bee-build.xml, we should build the 7Bee build tool and install, right?
> When I ran bootstrap script, it shows such error.
> ![image](https://user-images.githubusercontent.com/48024874/120422202-9fa7b180-c31c-11eb-8387-c7a80d7e850d.png)
> Maybe the central.maven.org to download jsch-0.1.53.jar was gone?
> If the bootstrap script is successfully ran, we should run this command `java -jar ./lib/bee.jar install` to install 7Bee build tool?

I have updated maven link, so it should build. The script will run install automatically.

**Comment by drogatkin** [comment]
Details on parameters:
   <!ENTITY android_sdk "/home/dmitriy/Android/Sdk">
You download SDK right, just provide its location as "~/Android/Sdk"
      <!ENTITY jdk_root "">
Leave it as is.
      <!ENTITY tjws_src "/home/dmitriy/projects/TJWS2/1.x">
Specify a directory where TJWS checked out and built.
      <!ENTITY jasper "/home/dmitriy/projects/jasper-7.0.75">
This most complex part, since required to check out Tomcat and then compile it with TJWS changes. Let me try to post the .jar in TJWS.
      <!ENTITY keystore "/home/dmitriy/Documents/android-publish.keystore">
You will need to create own certificate, let me know if you need help here.
      <!ENTITY alias "app_release">
Name with a certificate in the key store.
      <!ENTITY target "30">
Android JDK version, make sure it is installed in the Sdk.
      <!ENTITY build_tool "29.0.3">
This version should be in Sdk already.
      <!ENTITY build_directory "build">

**Comment by drogatkin** [comment]
Entity XML entries disappeared in my response, but you shouldn't have a problem to map my responses to them.

**Comment by jixu1031** [comment]
Dear @drogatkin 

Thank you very much for your answers!!!
I will try again to build using 7Bee tool.
Finally based on your article [ https://www.linkedin.com/pulse/how-migrate-android-project-use-gradle-build-tool-dmitriy-rogatkin/](url), I could build this app successfully in Android Studio.
Thanks again for your great work!!!
I'll let you know if I have any other issues while working.

**Comment by jixu1031** [comment]
Just one more question...
Is it also possible to build it in Eclipse? Because my friend is more familiar with Eclipse rather than Android Studio.

**Comment by drogatkin** [comment]
Unfortunately,Google dropped a support of the Eclipse Android plugin many years ago. Although Atjeews doesn't require modern Android API, it can't be used on Eclipse due Sdk structure change and the emulator communication. Even using 7Bee based build tool with Eclipse won't be beneficial.

**Comment by jixu1031** [comment]
OK, got it. Thank you!
